name: rel_zip_win

on:
  push:
    tags:
      - 'v*'   # タグ push 時に実行
      - '[0-9]*'   # 0, 1, 2...で始まるタグ（例: 1.0.0, 2.1.3 など）で実行

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      REL_NAME: "RelFile"

    steps:
      - uses: actions/checkout@v4

      - name: zip作成
        run: |
          zip -r "${REL_NAME}-${{ github.ref_name }}.zip"  dir1 dir2 Makefile README.md
      - run: ls -lh
      - run: echo "ZIPファイル名: ${REL_NAME}-${{ github.ref_name }}.zip"

      - name: リリースにアップロード
        uses: softprops/action-gh-release@v2
        with:
          files: "RelFile-${{ github.ref_name }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
